import { motion, AnimatePresence } from "framer-motion";
import { X } from "lucide-react";
import { useEffect } from "react";
import { playFanfare } from "@/lib/sounds";

const teko = { fontFamily: "Teko, sans-serif" };

interface ThemeRevealModalProps {
  open: boolean;
  onClose: () => void;
  theme: string;
  info?: string;
  isAutoGenerated?: boolean;
  competitionName?: string;
}

export default function ThemeRevealModal({
  open, onClose, theme, info, isAutoGenerated, competitionName,
}: ThemeRevealModalProps) {
  useEffect(() => {
    if (!open) return;
    playFanfare();
    // Auto-dismiss after 8s so it never traps the user
    const t = window.setTimeout(onClose, 8000);
    return () => window.clearTimeout(t);
  }, [open, onClose]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/90 backdrop-blur-md p-4"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.7, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0 }}
            transition={{ type: "spring", damping: 18, stiffness: 240 }}
            onClick={(e) => e.stopPropagation()}
            className="relative w-full max-w-sm rounded-2xl border border-white/10 bg-[#0b0b0d] overflow-hidden"
          >
            {/* Close */}
            <button
              onClick={onClose}
              className="absolute top-3 right-3 z-10 w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center text-white/60 hover:text-white transition"
              aria-label="Close"
            >
              <X className="w-4 h-4" />
            </button>

            {/* Header */}
            <div className="px-5 pt-8 pb-2">
              <p className="text-center text-[10px] tracking-[0.3em] text-white/40 uppercase font-bold">
                Theme
              </p>
              {competitionName && (
                <p className="text-center text-white/50 text-xs mt-1 truncate">
                  {competitionName}
                </p>
              )}
            </div>

            {/* Theme reveal */}
            <div className="px-5 pb-5">
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.35 }}
                className="text-center"
              >
                <h2
                  className="text-5xl text-white leading-none tracking-wide uppercase mt-3"
                  style={teko}
                >
                  {theme}
                </h2>
              </motion.div>

              <button
                onClick={onClose}
                className="mt-8 w-full h-12 rounded-xl bg-white hover:bg-white/90 text-black font-bold tracking-wider uppercase text-sm transition active:scale-[0.98]"
                style={teko}
              >
                Let's Go
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/* ── Auto theme generator — used when host didn't set one ───── */
const AUTO_THEMES: Array<{ theme: string; info: string }> = [
  { theme: "Sad Edit", info: "" },
  { theme: "Hype Edit", info: "" },
  { theme: "Phonk Edit", info: "" },
  { theme: "Nostalgia Edit", info: "" },
  { theme: "Anime Edit", info: "" },
  { theme: "Cinematic Edit", info: "" },
  { theme: "Glitch Edit", info: "" },
  { theme: "Jugg Edit", info: "" },
  { theme: "Velocity Edit", info: "" },
  { theme: "Slow-Mo Edit", info: "" },
  { theme: "Lyrical Edit", info: "" },
  { theme: "Funny Edit", info: "" },
  { theme: "Action Edit", info: "" },
  { theme: "Aesthetic Edit", info: "" },
  { theme: "Dark Edit", info: "" },
  { theme: "Romance Edit", info: "" },
  { theme: "Beat Sync Edit", info: "" },
  { theme: "Trailer Edit", info: "" },
];

export function pickAutoTheme(seed: string): { theme: string; info: string } {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return AUTO_THEMES[hash % AUTO_THEMES.length];
}