import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Trophy, X } from "lucide-react";
import { useEffect } from "react";
import { playFanfare } from "@/lib/sounds";

const teko = { fontFamily: "Teko, sans-serif" };

interface ThemeRevealModalProps {
  open: boolean;
  onClose: () => void;
  theme: string;
  info?: string;
  isAutoGenerated?: boolean;
  competitionName?: string;
}

export default function ThemeRevealModal({
  open, onClose, theme, info, isAutoGenerated, competitionName,
}: ThemeRevealModalProps) {
  useEffect(() => {
    if (!open) return;
    playFanfare();
    // Auto-dismiss after 8s so it never traps the user
    const t = window.setTimeout(onClose, 8000);
    return () => window.clearTimeout(t);
  }, [open, onClose]);

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/85 backdrop-blur-md p-4"
          onClick={onClose}
        >
          {/* Background flare */}
          <motion.div
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 2.5, opacity: [0, 0.6, 0] }}
            transition={{ duration: 1.4, ease: "easeOut" }}
            className="absolute inset-0 m-auto w-[420px] h-[420px] rounded-full bg-gradient-to-r from-amber-500/40 via-orange-500/30 to-red-500/20 blur-3xl"
          />

          <motion.div
            initial={{ scale: 0.7, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0 }}
            transition={{ type: "spring", damping: 18, stiffness: 240 }}
            onClick={(e) => e.stopPropagation()}
            className="relative w-full max-w-sm rounded-2xl border border-amber-400/40 bg-[#0b0b0d] shadow-[0_0_60px_rgba(251,191,36,0.35)] overflow-hidden"
          >
            {/* Close */}
            <button
              onClick={onClose}
              className="absolute top-3 right-3 z-10 w-8 h-8 rounded-full bg-white/5 hover:bg-white/10 flex items-center justify-center text-white/60 hover:text-white transition"
              aria-label="Close"
            >
              <X className="w-4 h-4" />
            </button>

            {/* Header strip */}
            <div className="relative px-5 pt-6 pb-4 bg-gradient-to-b from-amber-500/15 to-transparent">
              <motion.div
                initial={{ scale: 0, rotate: -90 }}
                animate={{ scale: 1, rotate: 0 }}
                transition={{ delay: 0.15, type: "spring", damping: 12 }}
                className="mx-auto w-14 h-14 rounded-full bg-amber-400/15 border border-amber-400/40 flex items-center justify-center mb-3"
              >
                <Trophy className="w-7 h-7 text-amber-400" />
              </motion.div>
              <p className="text-center text-[10px] tracking-[0.3em] text-amber-400/80 uppercase font-bold">
                Competition Started
              </p>
              {competitionName && (
                <p className="text-center text-white/70 text-sm mt-1 truncate">
                  {competitionName}
                </p>
              )}
            </div>

            {/* Theme reveal */}
            <div className="px-5 pb-5">
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.35 }}
                className="text-center"
              >
                <div className="flex items-center justify-center gap-2 mb-2">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                  <p className="text-[10px] tracking-[0.25em] text-white/50 uppercase font-bold">
                    {isAutoGenerated ? "Auto Theme" : "Your Theme"}
                  </p>
                  <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                </div>
                <h2
                  className="text-4xl text-white leading-none tracking-wide uppercase"
                  style={teko}
                >
                  {theme}
                </h2>
              </motion.div>

              {info && (
                <motion.p
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.55 }}
                  className="mt-4 text-center text-sm text-white/65 leading-relaxed"
                >
                  {info}
                </motion.p>
              )}

              <motion.div
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.85, type: "spring" }}
                className="mt-5 mx-auto w-fit px-4 py-1.5 rounded-full bg-emerald-500/15 border border-emerald-400/40"
              >
                <p className="text-emerald-300 text-xs font-bold tracking-[0.2em] uppercase">
                  Good Luck 🍀
                </p>
              </motion.div>

              <button
                onClick={onClose}
                className="mt-5 w-full h-11 rounded-xl bg-amber-400 hover:bg-amber-300 text-black font-bold tracking-wider uppercase text-sm transition active:scale-[0.98]"
                style={teko}
              >
                Let's Go
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/* ── Auto theme generator — used when host didn't set one ───── */
const AUTO_THEMES: Array<{ theme: string; info: string }> = [
  { theme: "Neon Nights", info: "Lean into glowing colors, cyberpunk vibes, and high-contrast city lights." },
  { theme: "Slow-Mo Mayhem", info: "Showcase your best ramps, freezes, and slow-motion impact moments." },
  { theme: "Beat Drop Frenzy", info: "Sync every cut to the beat. Make the drop hit harder than the song." },
  { theme: "Anime Energy", info: "Speedlines, color flashes, dramatic zooms — pure shonen energy." },
  { theme: "Cinematic Mood", info: "Letterbox bars, color grade deep, slow pans, emotional pacing." },
  { theme: "Retro VHS", info: "Grain, chromatic aberration, tape glitches, nostalgic warmth." },
  { theme: "Glitch Core", info: "Datamosh, RGB splits, frame stutters — controlled chaos." },
  { theme: "Velocity Edit", info: "Fast cuts, whip pans, momentum-driven transitions. No dead frames." },
  { theme: "Shadow & Light", info: "High contrast black-and-white. Let silhouettes do the talking." },
  { theme: "Dreamcore", info: "Soft glows, surreal transitions, hypnotic loops." },
  { theme: "Action Reel", info: "Punch-ins, impact frames, big-screen blockbuster pacing." },
  { theme: "Loopy Madness", info: "Seamless loops and infinite cuts. Make the viewer rewind." },
];

export function pickAutoTheme(seed: string): { theme: string; info: string } {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return AUTO_THEMES[hash % AUTO_THEMES.length];
}